Milestones 3, 4, 5 & 6: Styling sheet
kaysiz/microverse-newyork-times-clone pull request #7
Opened 2020-10-22 17:08 UTC by Andrik27001

1. Added markup & simple styling
2. Added Flexbox
3. Added floats
4. Positioned all elements

2020-10-22 18:48 UTC, MuriloRoque requested changes
## Status: Changes requested :red_circle: 

### Hello @Andrik27001 and @kaysiz :wave: 

### First of all, congratulations on your first project, it really looks great :clap: :clap: :clap: 

### Please, check my suggestions below in order to improve it:

- [x] I see that you only personalized the author's names in your README file, you should personalize the rest too. Specify the technologies you used, give a description and a name to your project, add a screenshot, and a Live Demo link.

- [x] Fix your stylesheet and images paths in your `index.html` file, I couldn't visualize them here, I had to remove the first slash (/) from the paths for them to work.

- [x] Your New York Times logo should be a link, just like in the original.

- [x] Please, align the text in the Editor's Picks section to the right of the images, currently, they are below the images and not aligned at all:

![Screenshot from 2020-10-22 15-29-44](https://user-images.githubusercontent.com/59691171/96914595-951a6500-147b-11eb-846c-0041d8377620.png)

- [ ] Please make sure to align this image to the center, just like you did with the ones above it:

![Screenshot from 2020-10-22 15-34-01](https://user-images.githubusercontent.com/59691171/96914996-1d006f00-147c-11eb-81ee-0871dbfd76b7.png)

- [ ] In the bottom part of the page, the styles are not right, the images are on top of one another. Make sure you follow the original design and apply the right CSS styles to it:

![Screenshot from 2020-10-22 15-35-25](https://user-images are not styledimages.githubusercontent.com/59691171/96915341-808a9c80-147c-11eb-9095-ea73f18267a6.png)

- [ ] It's a bad practice to use that many ID selectors for styles, please change them to class selectors.

- [ ] Please, consider creating classes for the properties below, you are repeating a lot of CSS properties. It's better to create a specific class for each of those properties and apply them to your HTML elements. For example: create a class named `flex` and give it `display: flex`, then apply this class to all of your HTML elements that you want to be flexed :+1: 

       13 |   display: flex;
       7 |   font-family: helvetica, arial, sans-serif;
       7 |   text-decoration: none;
       6 |   align-items: center;
       6 |   color: #333;
       6 |   font-weight: bold;

## Summary

- Your page is almost identical to the original, keep up the good work :muscle: 
- Your project is very well organized and your Pull Request description is professional :+1: 
- We just need to fix some of the issues before proceeding, alright? :smile: 

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-10-23 16:14 UTC, kaysiz approved these changes

2020-10-23 16:57 UTC, MarioDena requested changes
Hello! Great work implementing the requested changes! 🥇  However there are still some changes needed.

Changes Required 🔴 

- [ ] Please Remember to either delete or add to .gitignore unrelated files to this project for example (.vscode folder).

- [ ] Try to clean up your code of repeated rules (on your CSS), for example `display: flex;` is repeated 12 times. It's better to have many classes to avoid rule repetition. (same goes for `width: 100%;` `display: block;` `margin: 0 auto;` `color: #000;`)

After making the requested changes please re-submit your project for another review.

2020-10-24 16:35 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello again @kaysiz and @Andrik27001 :wave: 

### Thank you for making all of the requested changes, your project is approved, congratulations :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-10-24 16:41 UTC, merged